/**
 * Thin wrapper over browser.i18n.
 *
 * Translations live in `extension/public/_locales/<locale>/messages.json` and
 * are regenerated by `scripts/generate-locales.mjs` — edit that script, not the
 * JSON, so every locale stays in step with the English base.
 */

/**
 * WXT types getMessage against only the predefined `@@` names, because it can
 * only infer real message names when the @wxt-dev/i18n module is in use. Our
 * names are validated at build time by scripts/generate-locales.mjs instead,
 * which fails if any locale drifts from the English base.
 */
const getMessage = browser.i18n.getMessage as (name: string) => string;

/**
 * Returns the translated string, falling back to the key itself.
 *
 * getMessage returns an empty string for an unknown name rather than throwing,
 * which silently produces blank labels. Surfacing the key makes a missing
 * translation obvious in review instead of invisible.
 */
export function t(name: string): string {
  return getMessage(name) || name;
}

/**
 * Fills in every element tagged for translation.
 *
 *   <h2 data-i18n="sectionAppearance">Appearance</h2>
 *   <span data-i18n-title="pillAlreadyDarkTitle">…</span>
 *
 * The markup keeps readable English so the popup is still legible in source and
 * in devtools; this only replaces it at runtime.
 */
export function localiseDocument(root: ParentNode = document): void {
  root.querySelectorAll<HTMLElement>("[data-i18n]").forEach((element) => {
    const name = element.dataset.i18n;

    if (name) {
      element.textContent = t(name);
    }
  });

  root
    .querySelectorAll<HTMLElement>("[data-i18n-title]")
    .forEach((element) => {
      const name = element.dataset.i18nTitle;

      if (name) {
        element.title = t(name);
      }
    });
}
